### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by roniemartinez** [mattiasflodin/reckless#12]
How does this library respond to scalability? One example is multi-process logging (Possibly, multiple processes writing on the same file).

Thanks!

**Comment by mattiasflodin** [comment]
I haven't benchmarked multi-process logging, but with multiple processes there will be contention for two resources: CPU time for message formatting / buffering, and kernel I/O. Based on my existing benchmarks I know that reckless uses both less I/O and CPU time than the other libraries in the comparison, which means it should also perform better with multiple processes writing.

Strictly,  "scalability" in the sense "what speedup factor do I get if I double the number of processes" is really only limited by the OS you are running on, and which library you use doesn't matter. You will get better scalability if each process writes to its own log, instead of having every process write to the same file. The files can be joined later on by a post-mortem tool.

With multi-_threaded_ logging in reckless, you can hit a scalability roof if the background thread performing the logging maxes out the CPU core it is running on. Each logger object has only a single thread to perform formatting and disk I/O. But you're very unlikely to hit that roof unless you are logging hundreds of megabytes per second and have high-performance disk that can write data faster than the CPU can generate it. So, not likely to be an issue.

**Comment by roniemartinez** [comment]
Thanks a lot @mattiasflodin
